- name: variables at task level
  hosts: localhost
  vars:
   - money: "10000 RS"
     land: "100 acers"
  tasks:
   - name: inherit values from play
     ansible.builtin.debug:
      msg: "MONEY:{{money}}, LAND:{{land}}"
   - name:  inherit values from play and add and override
     vars:
      - money: "200000 RS"
        houses: "3 houses"
     ansible.builtin.debug:
      msg: "MONEY:{{money}}, LAND:{{land}}, HOUSES:{{houses}}"
       