- name: install packages
  hosts: localhost
  become: yes
  tasks:
   - name: install package
     ansible.builtin.yum:
      name: "{{item}}"
      state: installed
     loops:
      - nginx
      - mailx
      - postfix
      - cyrus-sasl-plain
