- name: install packages
  hosts: mongodb
  tasks:
   - name: install package
     ansible.builtin.yum:
      name: "{{item.name}}"
      state: "{{item.state}}"
     loop:
      - {name: 'nginx', state: 'absent'}
      - {name: 'postfix', state: 'installed'}
      - {name: 'cyrus-sasl-plain', state: 'absent'}
      - {name: 'mailx', state: 'installed'}