- name: Error Hanfling
  hosts: mongodb
  become: yes
  tasks:
   - block:
      - name: Install httpd package
        ansible.builtin.yum:
         name: httpd
         state: installed
     rescue:
      - name: Install tomcat7 package
        ansible.builtin.apt:
         name: tomcat7
         state: present
     always:
      - name: check url response
        ansible.builtin.uri:
         url: http://172.31.28.168
         status_code: 200
        

# If you want to run the ansible playbook with private key we should use below command before running below command we will do password less ssh connection between control server and managed node
#ansible-playbook -i inventory(path of inventory) --key-file=~/.ssh/id_rsa 17-exception_handling.yaml